// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using canvasync.Data;
using canvasync.Library.Dtos;

#nullable disable

namespace canvasync.Migrations
{
    [DbContext(typeof(CanvasDbContext))]
    [Migration("20260321082025_SyncCurrentModel")]
    partial class SyncCurrentModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LectureMember", b =>
                {
                    b.Property<string>("JoinedLecturesId")
                        .HasColumnType("text");

                    b.Property<string>("MembersId")
                        .HasColumnType("text");

                    b.HasKey("JoinedLecturesId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("LectureMember");
                });

            modelBuilder.Entity("canvasync.Library.Models.DrawingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<List<FactorDto>>>("Drawings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LectureId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DrawingData");
                });

            modelBuilder.Entity("canvasync.Library.Models.Lecture", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HostMemberId")
                        .HasColumnType("text");

                    b.Property<byte[]>("PdfFileBytes")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("HostMemberId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("canvasync.Library.Models.Member", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("LectureMember", b =>
                {
                    b.HasOne("canvasync.Library.Models.Lecture", null)
                        .WithMany()
                        .HasForeignKey("JoinedLecturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("canvasync.Library.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("canvasync.Library.Models.Lecture", b =>
                {
                    b.HasOne("canvasync.Library.Models.Member", "HostMember")
                        .WithMany("MyLectures")
                        .HasForeignKey("HostMemberId");

                    b.Navigation("HostMember");
                });

            modelBuilder.Entity("canvasync.Library.Models.Member", b =>
                {
                    b.Navigation("MyLectures");
                });
#pragma warning restore 612, 618
        }
    }
}
