// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using canvasync.Data;

#nullable disable

namespace canvasync.Migrations
{
    [DbContext(typeof(CanvasDbContext))]
    [Migration("20260207123041_AddDrawingData")]
    partial class AddDrawingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LectureMember", b =>
                {
                    b.Property<string>("JoinedLecturesId")
                        .HasColumnType("text");

                    b.Property<string>("MembersId")
                        .HasColumnType("text");

                    b.HasKey("JoinedLecturesId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("LectureMember");
                });

            modelBuilder.Entity("canvasync.Library.Models.DrawingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LectureId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DrawingData");
                });

            modelBuilder.Entity("canvasync.Library.Models.Lecture", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HostMemberId")
                        .HasColumnType("text");

                    b.Property<byte[]>("PdfFileBytes")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("HostMemberId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("canvasync.Library.Models.Member", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("LectureMember", b =>
                {
                    b.HasOne("canvasync.Library.Models.Lecture", null)
                        .WithMany()
                        .HasForeignKey("JoinedLecturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("canvasync.Library.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("canvasync.Library.Models.DrawingData", b =>
                {
                    b.OwnsOne("canvasync.Library.Dtos.DrawingsDto", "Drawings", b1 =>
                        {
                            b1.Property<int>("DrawingDataId")
                                .HasColumnType("integer");

                            b1.HasKey("DrawingDataId");

                            b1.ToTable("DrawingData");

                            b1
                                .ToJson("Drawings")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DrawingDataId");

                            b1.OwnsMany("canvasync.Library.Dtos.PageDto", "PageDtos", b2 =>
                                {
                                    b2.Property<int>("DrawingsDtoDrawingDataId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("Height")
                                        .HasColumnType("integer");

                                    b2.Property<string>("ImgData")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int>("PageIndex")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Width")
                                        .HasColumnType("integer");

                                    b2.HasKey("DrawingsDtoDrawingDataId", "__synthesizedOrdinal");

                                    b2.ToTable("DrawingData");

                                    b2.WithOwner()
                                        .HasForeignKey("DrawingsDtoDrawingDataId");

                                    b2.OwnsMany("canvasync.Library.Dtos.FactorDto", "FactorDtos", b3 =>
                                        {
                                            b3.Property<int>("PageDtoDrawingsDtoDrawingDataId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("PageDto__synthesizedOrdinal")
                                                .HasColumnType("integer");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            b3.Property<float>("BoxHeight")
                                                .HasColumnType("real");

                                            b3.Property<float>("BoxLeft")
                                                .HasColumnType("real");

                                            b3.Property<float>("BoxTop")
                                                .HasColumnType("real");

                                            b3.Property<float>("BoxWidth")
                                                .HasColumnType("real");

                                            b3.Property<int>("FactorType")
                                                .HasColumnType("integer");

                                            b3.Property<string>("PaintColor")
                                                .HasColumnType("text");

                                            b3.Property<bool>("PaintIsAntialias")
                                                .HasColumnType("boolean");

                                            b3.Property<float>("PaintStrokeWidth")
                                                .HasColumnType("real");

                                            b3.Property<int>("PaintStyle")
                                                .HasColumnType("integer");

                                            b3.HasKey("PageDtoDrawingsDtoDrawingDataId", "PageDto__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("DrawingData");

                                            b3.WithOwner()
                                                .HasForeignKey("PageDtoDrawingsDtoDrawingDataId", "PageDto__synthesizedOrdinal");

                                            b3.OwnsOne("canvasync.Library.Dtos.PenPathDto", "PenPathDto", b4 =>
                                                {
                                                    b4.Property<int>("FactorDtoPageDtoDrawingsDtoDrawingDataId")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("FactorDtoPageDto__synthesizedOrdinal")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("FactorDto__synthesizedOrdinal")
                                                        .HasColumnType("integer");

                                                    b4.Property<string>("PenPathData")
                                                        .IsRequired()
                                                        .HasColumnType("text");

                                                    b4.HasKey("FactorDtoPageDtoDrawingsDtoDrawingDataId", "FactorDtoPageDto__synthesizedOrdinal", "FactorDto__synthesizedOrdinal");

                                                    b4.ToTable("DrawingData");

                                                    b4.WithOwner()
                                                        .HasForeignKey("FactorDtoPageDtoDrawingsDtoDrawingDataId", "FactorDtoPageDto__synthesizedOrdinal", "FactorDto__synthesizedOrdinal");
                                                });

                                            b3.OwnsMany("canvasync.Library.Dtos.TextBlockDto", "TextBlockDtos", b4 =>
                                                {
                                                    b4.Property<int>("FactorDtoPageDtoDrawingsDtoDrawingDataId")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("FactorDtoPageDto__synthesizedOrdinal")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("FactorDto__synthesizedOrdinal")
                                                        .HasColumnType("integer");

                                                    b4.Property<int>("__synthesizedOrdinal")
                                                        .ValueGeneratedOnAdd()
                                                        .HasColumnType("integer");

                                                    b4.Property<string>("TextBlockFontFamily")
                                                        .HasColumnType("text");

                                                    b4.Property<float>("TextBlockFontSize")
                                                        .HasColumnType("real");

                                                    b4.Property<int>("TextBlockFontSlant")
                                                        .HasColumnType("integer");

                                                    b4.Property<float>("TextBlockFontWeight")
                                                        .HasColumnType("real");

                                                    b4.Property<float>("TextBlockHeight")
                                                        .HasColumnType("real");

                                                    b4.Property<float>("TextBlockLeft")
                                                        .HasColumnType("real");

                                                    b4.Property<string>("TextBlockPaintColor")
                                                        .HasColumnType("text");

                                                    b4.Property<bool>("TextBlockPaintIsAntialias")
                                                        .HasColumnType("boolean");

                                                    b4.Property<float>("TextBlockPaintStrokeWidth")
                                                        .HasColumnType("real");

                                                    b4.Property<int>("TextBlockPaintStyle")
                                                        .HasColumnType("integer");

                                                    b4.Property<string>("TextBlockText")
                                                        .IsRequired()
                                                        .HasColumnType("text");

                                                    b4.Property<float>("TextBlockTop")
                                                        .HasColumnType("real");

                                                    b4.Property<float>("TextBlockWidth")
                                                        .HasColumnType("real");

                                                    b4.HasKey("FactorDtoPageDtoDrawingsDtoDrawingDataId", "FactorDtoPageDto__synthesizedOrdinal", "FactorDto__synthesizedOrdinal", "__synthesizedOrdinal");

                                                    b4.ToTable("DrawingData");

                                                    b4.WithOwner()
                                                        .HasForeignKey("FactorDtoPageDtoDrawingsDtoDrawingDataId", "FactorDtoPageDto__synthesizedOrdinal", "FactorDto__synthesizedOrdinal");
                                                });

                                            b3.Navigation("PenPathDto")
                                                .IsRequired();

                                            b3.Navigation("TextBlockDtos");
                                        });

                                    b2.Navigation("FactorDtos");
                                });

                            b1.Navigation("PageDtos");
                        });

                    b.Navigation("Drawings")
                        .IsRequired();
                });

            modelBuilder.Entity("canvasync.Library.Models.Lecture", b =>
                {
                    b.HasOne("canvasync.Library.Models.Member", "HostMember")
                        .WithMany("MyLectures")
                        .HasForeignKey("HostMemberId");

                    b.Navigation("HostMember");
                });

            modelBuilder.Entity("canvasync.Library.Models.Member", b =>
                {
                    b.Navigation("MyLectures");
                });
#pragma warning restore 612, 618
        }
    }
}
